# The URL the site will be built for
base_url = "https://Borlaag.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Site title
title = "Børlaag"

# Website theme, using slightly customized version of 'zola-paper'
# https://github.com/schoenenberg/zola-paper
theme = "zola-paper"

taxonomies = [
  {name = "tags", rss = true, paginate_by = 10},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "dracula"

[extra]
# Put all your custom variables here
links = [
  { name = "GitHub", url = "https://github.com/Borlaag"},
  { name = "Twitter", url = "https://twitter.com/Borlaag"},
  { name = "Matrix", url = "https://matrix.to/#/@borlaag:matrix.org"},
]
